name: Create Sentry release
description: Creates a Sentry release
inputs:
  environment:
    default: development
    description: Environment for the release
  org:
    description: Sentry organization slug
    required: false
  project:
    description: Sentry project slug
    required: false
  sentry-auth-token:
    description: Sentry authentication token (if creating a release in Sentry)
    required: false
  sourcemaps-artifacts-name:
    description: Name of the sourcemap artifacts to download
    required: false
  sourcemaps-path:
    description: Path (relative to working directory) to of the sourcemaps
  version:
    description: Identifier that uniquely identifies the release
    required: false
runs:
  using: composite
  steps:
    - name: Download artifacts
      if: ${{ inputs.sourcemaps-artifacts-name }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.sourcemaps-artifacts-name }}
        path: ${{ inputs.sourcemaps-path }}
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.org }}
        SENTRY_PROJECT: ${{ inputs.project }}
      with:
        environment: ${{ inputs.environment }}
        set_commits: skip
        sourcemaps: ./${{ inputs.sourcemaps-path }}
        version: ${{ inputs.version && inputs.version || github.sha }}
